### ISSUE TITLE
Add plaything.io to the list

### ISSUE THREAD

**Issue by Flutterish** [buttplugio/awesome-buttplug#15]
I made a project which lets you share control over various devices through a node.js server and web browser client(s). The rooms you join have real-time sharing of cursors and state of control elements. There is a video in the readme. It integrates buttplug.io as a pool of devices you can share.

Essentially, this is a multiplayer remote control panel.

https://github.com/Flutterish/plaything.io

**Comment by qdot** [comment]
Updated, finally. >.>
