### ISSUE TITLE
OSR-2 & VRChat/NeosVR

### ISSUE THREAD

**Issue by udgtehsy** [buttplugio/awesome-buttplug#16]
Is there any way the OSR-2 could interface with VR multiplayer games such as VRChat or NeosVR? I haven't seen any implementation for this and was wondering if I'm not looking hard enough, or if there really is the need for someone to develop something like this.

**Comment by qdot** [comment]
This would be a better question on one of the mods we support versus this repo, but the OSR-2 might work with the beta branch of VGB, which has stroker support. I still need to test it. Best to check on our discord, https://discord.buttplug.io
