### ISSUE TITLE
Plug₂in for RPG Maker MV

### ISSUE THREAD

**Issue by qazmlp** [buttplugio/awesome-buttplug#17]
I made this plugin earlier this month after seeing the Elden Ring thread: https://qazm.itch.io/plug-in-for-rpg-maker-mv

It's a bit rudimentary at this point since it was spur of the moment and mostly for learning, but I think I've still come up with something that's useful. I may expand on it if there's interest.

This is intentionally not a full-blown buttplug client but instead aims to make it easy to enhance existing scenes with interesting opt-in vibration features. As such, you don't get device enumeration through this library, but instead there's a bit of preference management and a pattern scheduler built into it directly.

The plug₂in won't connect to devices on its own (for now?, but I don't see how to make that work nicely), so Intiface is required.

**Comment by qdot** [comment]
Updated, finally. >.>
