### ISSUE TITLE
RiskOfRumble

### ISSUE THREAD

**Issue by VoidField101** [buttplugio/awesome-buttplug#29]
Someone mentioned in the discord a Risk Of Rain 2 mod exist called RiskOfRumble.

It also seems to use Buttplug C#
I found the source code here: https://github.com/mistername/RiskOfRainModding/tree/master/RiskOfRumble
And the mod itself is on Thunderstore: https://thunderstore.io/package/MisterKinky/RiskOfRumble/

Haven't tested it myself.

**Comment by qdot** [comment]
Added, thanks!
