### ISSUE TITLE
Beadi (Node-Based Editor)

### ISSUE THREAD

**Issue by ThatBatLuna** [buttplugio/awesome-buttplug#32]
I created [Beadi](https://github.com/ThatBatLuna/Beadi) as a spinoff / unofficial successor to the [Buttplug Editor](https://github.com/MaidKun/buttplug-editor) Project - which seems to be discontinued and has some rough edges.

It is hosted on github pages - with the goal of minimal setup time (noone wants to fight with npm, etc. when stumbling upon a funny project). 

I'd really love it to be listed on awesome-buttplug.

My suggestion for the entry:
```
- [Beadi](https://thatbatluna.github.io/Beadi/)
  - Free, open source, repo at https://github.com/ThatBatLuna/Beadi  
  - Web based (Cross platform, either via browsers or Intiface Desktop)
  - Visual node-based editor for programming Buttplug-compatible toys
```

Thanks a lot,
Luna

**Comment by qdot** [comment]
This is amazing! A few people in the discord have been playing with it already. :D

I'll get this added, thanks for putting it together!

**Comment by ThatBatLuna** [comment]
Amazing, I'll need to check out the discord to get some feedback lol
