### ISSUE TITLE
Skyrim and Fallout 4 Support

### ISSUE THREAD

**Issue by CrypticCherry** [buttplugio/awesome-buttplug#36]
https://github.com/MinLL/GameInterfaceForToys / https://www.loverslab.com/files/file/22380-gift-game-interface-for-toys-skyrim-le-se-ae-vr-fallout-4/ (All Skyrim Versions and Fallout 4)

https://virginmarie1.wixsite.com/toys / https://virginmarie1.wixsite.com/toys/post/how-to-make-toys-vibrate-real-life-accessories (Skyrim SE and LE)

**Comment by qdot** [comment]
Wow, hadn't seen either of these, thanks for pointing them out!

**Comment by qdot** [comment]
Added.
