### ISSUE TITLE
Ahegao Detector

### ISSUE THREAD

**Issue by Sir-Prise** [buttplugio/awesome-buttplug#38]
It would be nice if you could add my [Ahegao Detector](https://ahegao-detector.netlify.app/) to the list.

It's a website where you connect your webcam and toy. The toy vibrates whenever you make an "ahegao" face. The longer you can hold the face, the higher is the intensity.

I haven't updated the buttplug library in over two years, though.

[Repo](https://github.com/Sir-Prise/ahegao-detector)

**Comment by qdot** [comment]
... How the fuck do I not already have this on the list D:

As for the buttplug library, I've updated the js client, but there's not an updated WASM blob yet so you'd only get updated calls out to desktop/mobile Intiface Central.

**Comment by qdot** [comment]
Added
