### ISSUE TITLE
Healing is Fun (obsolete)

### ISSUE THREAD

**Issue by Sir-Prise** [buttplugio/awesome-buttplug#39]
I once made [Healing is Fun](https://healing-is-fun.netlify.app/), a website that controls the toy while playing Overwatch 1 based on the "on fire" meter. Since Overwatch 1 can't be played anymore, my website doesn't work either. Unfortunally, I never heard of anyone using my website so I'll probably not update it for Overwatch 2.

However, I like the concept that it runs entirely in the browser, as it's easier for casual users to use and also much more secure than having to download and run a software (this was the entire point why I made this).

You can decide if you want to add it to the list despite not working anymore. The only reason is that it could be an inspiration for other developers to create their games as web app.

[Repo](https://github.com/Sir-Prise/healsluts)

**Comment by qdot** [comment]
Yeah I'm looking at adding "defunct" projects because ideas and templates are still pretty important. Thanks!

**Comment by qdot** [comment]
Added to new "deprecated" portion of Awesome list
