### ISSUE TITLE
Stash video player

### ISSUE THREAD

**Issue by Boor1995** [buttplugio/awesome-buttplug#42]
Hello amazing Team buttplug,

Could you collaborate with Stash porn organiser so many interactive toys will be able to use a nice interface for their local videos. Stash already plays scripts but is currently only accessible for the Handy mastrubator.

Stash is an great way to watch and organise local porn videos while it’s all web based. It also is possible to connect VR movies with Stash. Myself as Mac user is missing a good local media video player to connect it with my Kiiroo Keon (or is there one?). Stash porn organiser, since it’s webbased is available for a wide array of devices(incl. both PC and Mac) so it will be useful for a large base of users not just Mac.

Check: https://github.com/stashapp/stash

Unfortunately I’m not as techsavy so please correct me if what I’m saying is incorrect, impossible or that you have a better solution/idea.

Kind regards,

Boris

**Comment by qdot** [comment]
This is already being worked on: https://github.com/stashapp/stash/pull/3502

**Comment by Boor1995** [comment]
Thank you! 💪🏻

**Comment by 4cz36sae** [comment]
Is there any interest in revisiting this? Looks like its been closed on both sides.

**Comment by Boor1995** [comment]
Yes there is still interest. Previously there has been worked on it but there was a bug that couldn’t be resolved at the time, see link in previous comment: stash#3502.

I don’t know if the bug has been resolved now.
