### ISSUE TITLE
RiskOfRumble Not turning on?

### ISSUE THREAD

**Issue by Dusty622** [buttplugio/awesome-buttplug#50]
i got my lovense Lush 3 connected to intiface and i have RiskOfRumble mod installed but it doesnt seem to turn on? shouldnt it automatically connect or what do i gotta do? Is RiskOfRumble out of date not working with SOTV dlc update?
![1](https://github.com/buttplugio/awesome-buttplug/assets/101378977/d3595c11-ac15-4adf-b295-37fe4ec565c5)
![2](https://github.com/buttplugio/awesome-buttplug/assets/101378977/8228e09c-ac3a-4813-993d-3bed3c9fe47a)

**Comment by qdot** [comment]
Yeah the RoR2 mod doesn't work right now and needs updates. It's not my mod but I've taken a look at it and I think I can fix it. I've got it on my todo list because I'm getting a LOT of questions about it, just gotta find time. Hopefully this week.

**Comment by exp111** [comment]
Uploaded a fixed version: [Thunderstore](https://thunderstore.io/package/exp111/RiskOfRumble/)/[GitHub](https://github.com/exp111/RoR2Stuff/tree/master/RiskOfRumble)
