### ISSUE TITLE
Describing FFXIV Vibe Plugin as free, while technically correct, is misleading.

### ISSUE THREAD

**Issue by silvenlily** [buttplugio/awesome-buttplug#62]
FFXIV Vibe Plugin is currently described as
"Free, open source, repo at https://github.com/kaciexx/FFXIV_Vibe_Plugin"
This is accurate, however some features of the plugin are disabled without paying a monthly subscription.
It should probably be changed to something like:
"Free with optional subscription, open source, repo at https://github.com/kaciexx/FFXIV_Vibe_Plugin"

(Sorry for edits, fat fingered the enter button as I was typing the title and I also can't spell or grammar apparently)

**Comment by qdot** [comment]
Oh, wasn't aware of the subscription, thanks! I'll get that updated soon.

**Comment by Xpahtalo** [comment]
It's also no longer open source. The github contains related stuff, but no source.

**Comment by qdot** [comment]
@Xpahtalo Should I throw AS Redux Reborn on the list while I'm at it?

**Comment by Xpahtalo** [comment]
Not quite yet, It's usable, but I'm going to be making some changes that will break stuff for anyone that starts now. I can open a PR once it's more accessible.

**Comment by qdot** [comment]
Added update.
