### ISSUE TITLE
team frotress two

### ISSUE THREAD

**Issue by fionafibration** [buttplugio/awesome-buttplug#63]
Hello, I recently finished a Team Fortress 2 buttplug,io control script over at [fionafibration/team-frotress-2](https://github.com/fionafibration/team-frotress-2/), and was wondering if it is of sufficient quality to include in this list

Thanks!

**Comment by qdot** [comment]
Added a while ago, just forgot to close this. :)

**Comment by fionafibration** [comment]
Hello, just wanted to mention that this also works for Linux and it's currently listed as Win 10+ only, thanks and sorry for the bother
