### ISSUE TITLE
Remove OsuToy

### ISSUE THREAD

**Issue by ayvacs** [buttplugio/awesome-buttplug#74]
OsuToy is running on an unstable beta build of Osu. It's four years behind in commits, lacking numerous major updates. It requires you to download [a five-year-old .NET release that went out of support four years ago.](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1.0/3.1.0.md?WT.mc_id=dotnet-35129-website) \*Yes, that specific version -- it did not work with any of the 32 security patches that came after it.\* The author has not been active on GitHub in three years either. After all of the setup, the program simply does not work.

I kindly ask that you remove it from the list so that people don't get their hopes up and waste a ton of time trying to make it work for nothing. Thank you!

**Comment by qdot** [comment]
Yeah I'll move it to the deprecated section. I've been talking to people about a new version, but there doesn't really seem to be an agreement on how integration should work, since the osu people don't want mods happening
