### ISSUE TITLE
what happened to monsieursoPythonPlayer repo?

### ISSUE THREAD

**Issue by johnlong21** [buttplugio/awesome-buttplug#93]
recently noticed the repo no longer exists along with the account. does anyone know what happened or has a more current fork as i have a copy via zip though it was from the initial creation and does not have any changes made?

**Comment by qdot** [comment]
Ugh, this happens every so often. People just disappear off the net. I'll move the package to deprecated.

**Comment by johnlong21** [comment]
hello, i have uploaded a early fork of the program at https://github.com/johnlong21/monsieursoFunscriptPlayer in case anyone is interested in the program though i do not know if it is still functional
